### PR TITLE
Add missing include <assert.h>

### PR DESCRIPTION
**Pull request by Uglymotha**
checkers.c: In function 'start_checker_thread':
checkers.c:392:9: error: implicit declaration of function 'assert' [-Werror=implicit-function-declaration]
  392 |         assert(ctx && ctx->cls && ctx->cls->thread);
      |         ^~~~~~
checkers.c:13:1: note: 'assert' is defined in header '<assert.h>'; did you forget to '#include <assert.h>'?

### CODE REVIEW

**Comment by xosevp** [comment]
Patches should be posted to dm-devel list, see README.

**Comment by mwilck** [comment]
Well this is simple enough to be merged without going through the mailing list, I suppose. But we still won't be using a PR workflow.

@Uglymotha, please add a Signed-off-by line.

**Comment by mwilck** [comment]
When the s-o-b is added, I'll push this to https://github.com/openSUSE/multipath-tools/tree/queue and include it into the next PR here.

(on those systems where I was testing, `assert.h` is implicitly included via the liburcu headers. But that's bad style, so I agree it should be added explicitly).

**Comment by mwilck** [comment]
@Uglymotha, our policy is to add an s-o-b to every commit. If you can't provide an updated patch, I'll recreate your patch with my s-o-b, giving you credit with a `Reported-by:` tag. Anyway, I'll wait a few more days.

**Comment by Uglymotha** [comment]
Hi,

Apologies for the late reaction, I was on vacation last week. Commit message has been amended with signed-off-by.

-Sietse

**Pull request closed without merging**
