### PR TITLE
multipath-tools 0.9.5

### LINKED ISSUE #45: Failed to send SCSI Registration to anyone of LUNs after mapping a large number of extern LUNS.
### Procedure:
Step1: 1024 LUNs (16 paths) for an external storage are mapping  to the host, then run rescan-scsi-bus.sh to produce 1024 disk.
Step2:  Manually issues a registration command to one of LUNs, receive timeout error.
mpathpersist -o -I -S 0x000000003320095c /dev/dm-117
But if I sent a registration command with sg_persist -o -I -S 0x000000003320095c /dev/dm-117, that was successful.
According the error log, I found that mpathpersist send msg of saving prkey to multipathd timeout  when I config reservation_key:
```
defaults {
	path_checker            tur
	no_path_retry           18
	path_grouping_policy    group_by_prio
	prio                    const
	deferred_remove         yes
	uid_attribute           "ID_SERIAL"
	reassign_maps           no
	failback                immediate
	log_checker_err         once
	reservation_key         "file"  // this item
}
```
### Root Cause: The recv package cannot be recievd after fixed **4 seconds** timeout, because multipathd spent more than 4 seconds to excute PARSE, which triggers vector lock collision  with checkerloop.
```
#define DEFAULT_REPLY_TIMEOUT	4000
static int do_update_pr(char *alias, char *arg)
{
        ......
	condlog (2, "%s: pr message=%s", alias, str);
	if (send_packet(fd, str) != 0) {
		condlog(2, "%s: message=%s send error=%d", alias, str, errno);
		mpath_disconnect(fd);
		return -1;
	}
	ret = recv_packet(fd, &reply, DEFAULT_REPLY_TIMEOUT);
	if (ret < 0) {
		condlog(2, "%s: message=%s recv error=%d", alias, str, errno);
		ret = -1;
	}
       ......
}
```
### Solution Suggestion:  Modify client timeout to uxsock_timeout value rather than DEFAULT_REPLY_TIMEOUT , that  will be  consistent with server, and that would make more sense: Client wait timeout should be more than Server excecution Timeout, 
considering the transmission delay. After that, uxsock_timeout  in /etc/multipath.conf can be modified to more than default value such as 10 seconds.

### LINKED ISSUE #54: IO process is D+ when path_checker is tur and there some problem in backstores
Here is a test. We use tur path_checker and echo offline to backstores, then  we write to multipath devices on client.
The IO process becomes D+ because request queue in kernel. We find  the path will be down->up->down->up and no_path_retry doesn't work because the tur check is OK but IO is fail.

This problem can be solved if we use directio path_checker or set no_path_retry fail. However, we want to use tur path_checker when there are thousands of multiparty devices. Do you have a good idea about this problem?

### LINKED ISSUE #56: Multipath aborts discovery of SAS devices lacking SCSI_VENDOR field
Some SAS devices (in this case Seagate factory recertified 'white label' drives) may come with the Vendor field blank. This causes Multipath to fail to complete the discovery of those devices. Manually adding associated wwid's to multipath.conf has no effect.

`multipath -v9` showing a pair of the suspect SAS devices (note that the process ends after the size check, where normally the next entry is vendor)
```
Nov 12 23:36:22 | Discover device /sys/devices/pci0000:d7/0000:d7:02.0/0000:da:00.0/host19/port-19:0/expander-19:0/port-19:0:1/expander-19:1/port-19:1:0/end_device-19:1:0/target19:0:1/19:0:1:0/block/sdjp
Nov 12 23:36:22 | 65:304: dev_t not found in pathvec
Nov 12 23:36:22 | sdjp: udev property ID_WWN whitelisted
Nov 12 23:36:22 | sdjp: mask = 0x3f
Nov 12 23:36:22 | sdjp: dev_t = 65:304
Nov 12 23:36:22 | open '/sys/devices/pci0000:d7/0000:d7:02.0/0000:da:00.0/host19/port-19:0/expander-19:0/port-19:0:1/expander-19:1/port-19:1:0/end_device-19:1:0/target19:0:1/19:0:1:0/block/sdjp/size'
Nov 12 23:36:22 | sdjp: size = 31251759104
Nov 12 23:36:22 | Discover device /sys/devices/pci0000:d7/0000:d7:02.0/0000:da:00.0/host19/port-19:0/expander-19:0/port-19:0:1/expander-19:1/port-19:1:1/end_device-19:1:1/target19:0:2/19:0:2:0/block/sdjq
Nov 12 23:36:22 | 65:320: dev_t not found in pathvec
Nov 12 23:36:22 | sdjq: udev property ID_WWN whitelisted
Nov 12 23:36:22 | sdjq: mask = 0x3f
Nov 12 23:36:22 | sdjq: dev_t = 65:320
Nov 12 23:36:22 | open '/sys/devices/pci0000:d7/0000:d7:02.0/0000:da:00.0/host19/port-19:0/expander-19:0/port-19:0:1/expander-19:1/port-19:1:1/end_device-19:1:1/target19:0:2/19:0:2:0/block/sdjq/size'
Nov 12 23:36:22 | sdjq: size = 31251759104
```

`udevadm info` output appears normal vs. other SAS devices except the following two fields are missing:
```
SCSI_VENDOR
SCSI_VENDOR_ENC
```

`smartctl -a -d scsi` output from one of the drives:
```
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.15.64-1-pve] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, [www.smartmontools.org](http://www.smartmontools.org/)

=== START OF INFORMATION SECTION ===
Vendor:
Product:              OOS16000G
Revision:             OOS1
Compliance:           SPC-5
User Capacity:        16,000,900,661,248 bytes [16.0 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c500d776128b
Serial number:        00000PJM0000C1507RXB
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Sun Nov 13 14:04:50 2022 EST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
```

### LINKED ISSUE #65: multipathd started leads to initrd blocked.
With 11f0440 commit, we meet a problem.

When there is a multipath device in initrd, multipathd will be actived becasue of dracut/modules.d/90multipath/multipathd-needshutdown.sh running. This lead to  initrd-cleanup.service can't be run and switch root fails. The initrd is blocked.

https://github.com/dracutdevs/dracut/issues/2289

### PR DESCRIPTION
**Pull request by mwilck**
Hi Christophe,

it's a relatively small PR this time, mostly bug fixes.

@bmarzins (15):
      multipathd: make pr registration consistent
      libmultipath: make prflag an enum
      multipathd: handle no active paths in update_map_pr
      multipathd: add missing newline to cli_del_map reply
      libmultipath: skip extra vector work in remove_maps
      libmultipath: orphan paths if coalesce_paths frees newmp
      libmultipath: use select_reload_action in select_action
      libmultipath: select resize action even if reload is forced
      libmultipath: cleanup ACT_CREATE code in select_action
      libmultipath: keep renames from stopping other multipath actions
      multipath.rules: fix "smart" bug with failed valid path check
      libmultipath: return 'pending' state when port is in transition (fixes #60)
      libmultipath: set init failure message when init fails
      libmultipath: reset nr_timeouts if we freed the context
      libmultipath: limit paths that can get wwid from environment

@brianatpurestorage  (1):
      libmultipathd: Avoid parsing errors due to unsupported designators

@dirkmueller (1):
      multipath-tools tests: use assert_true/false instead of assert() (fixes #63)

@mwilck (11):
      libmultipath: is_path_valid(): check if device is in use
      libmpathpersist: use conf->timeout for updating persistent reservations (fixes #45)
      libmultipath: pathinfo: don't fail for devices lacking INQUIRY properties (fixes #56)
      libmultipath: bump ABI version to 18.0.0
      libmpathpersist: fix resource leak in update_map_pr()
      libmultipath.version: bump symbol version of get_uid
      multipath-tools Makefiles: handle dependency files correctly
      multipathd.service: remove "Also=multipathd.socket" (fixes #65)
      libmultipath: use directio checker for LIO targets (fixes #54)
      GitHub workflows (basic): remove Ubuntu 18.04, add 22.04
      libmultipath: bump version to 0.9.5

@thesamesam (1):
      multipath-tools tests: fix quoting of CFLAGS in Makefile

All patches have been reviewed, except for the version bumps and the GitHub workflow changes (as usual).

### CODE REVIEW

**Comment by mwilck** [comment]
The CI job for Alpine has failed to download the sources. The [same job for the code](https://github.com/openSUSE/multipath-tools/actions/runs/4504935481) has succeeded in the openSUSE repo. @cvaroqui, if you have time, please just restart the job (I have no permissions to do that).

**Comment by cvaroqui** [comment]
@mwilck done

**Comment by mwilck** [comment]
Coverity scan found no new defects.

**Comment by mwilck** [comment]
I apologize for the multiple updates, I was having some fun with the update of the basic-build-and-ci GitHub workflow from Ubuntu bionic top jammy, and it took me a few attempts to get it right.

**Comment by mwilck** [comment]
Hold on once more, we need another fixup for #54.

**Review by bmarzins — APPROVED** [review]
Looks good to me.

**Pull request merged**
