### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by mwilck**
Hi Christophe,

here is another multipath-tools update. I've taken the liberty to bump the version to 0.8.9 already. It's mostly a bug fix release. The most important new feature is the support for FC Fibre Performance Impact Notifications (FPIN) contributed by Muneendra Kumar.

Regards
Martin

@bmarzins  (12):
      libmultipath: embed dm_info in multipath structure
      multipathd: update dm_info on multipath change events
      multipathd: avoid unnecessary path read-only reloads
      libmultipath: fix DI_NOIO pathinfo PATH_PENDING handling
      libmultipath: simplify out __set_no_path_retry()
      libmultipath: don't enter recovery mode with pending paths
      libmultipath: fix disassemble status for historical-service-time PS
      libmultipath: make helper function to trigger path uevents
      multipathd: trigger udev change on path addition
      libmultipath: use asprintf() to allocate prefixed_uuid
      multipathd: disallow changing to/from fpin marginal paths on reconfig
      libmultipath: fix printing native nvme multipath topology.

@mwilck (23):
      multipathd.service: remove LimitCORE=infinity directive
      multipathd.service: don't load SCSI device handler modules
      multipathd.service: add dependency on initrd-cleanup.service
      multipathd.service: drop dependencies on iscsi and iscsid
      libmpathpersist: split public and internal API
      multipathd: remove duplicate definitions from main.h
      libmpathpersist/multipathd: remove duplicate definition
      libmpathpersist: remove __STDC_FORMAT_MACROS
      libmpathpersist: cleanup mpathpr.h
      libmultipath.version: bump major version
      multipath/Makefile: use $(udevrulesdir)
      multipath-tools: Makefile.inc: delete obsolete comment
      multipath-tools: install modules-load.d/multipath.conf
      multipathd.service: drop ExecStartPre for loading dm-multipath
      multipath: Makefile: modules-load.d file for SCSI device handlers
      README.md: add basic information about building multipath-tools
      libmultipath: hwtable: use ALUA for all LIO targets
      kpartx.rules: skip MD devices
      libmultipath: enable linear ordering of bus/proto tuple
      libmultipath: use bus_protocol_id() in snprint_path_protocol()
      libmultipath: enable defining a static bitfield
      libmultipath: only warn once about unsupported dev_loss_tmo
      Bump version to 0.8.9

@muneendramandala  (1):
      multipathd: handle fpin events

@thesamesam (1):
      build: don't compress man pages (fixes #24)
 
@trofi (6):
      kpartx/devmapper.c: fix unused-but-set variable error
      kpartx/devmapper.c: fix unused variable error
      multipath-tools: autodiscover libdevmapper.h headers
      multipath-tools: autodiscover libudev.h headers
      multipath-tools: allow passing non-standard linux-headers location
      multipath-tools: avoid using GZIP Makefile variable
      (fixes #23)

@steffen-maier (2):
      libmultipath: support host adapter name lookup for s390x ccw bus
      libmultipath: add %L path wildcard for 64-bit hex LUN

@Uglymotha (1):
      Add missing include <assert.h> (fixes #25)

@xosevp (2):
      multipath-tools: fix misspellings
      multipath-tools: remove duplicate headers

### CODE REVIEW

**Comment by cvaroqui** [comment]
Hello, thank you for preparing this PR. What about the ABI test in error ?

**Comment by mwilck** [comment]
> Hello, thank you for preparing this PR. What about the ABI test in error ?

This failure means that the ABI has changed wrt the "master" branch. This is normal, and it's reflected in the PR by the changes in `libmultipath.version` (major version bump) and `libmpathpersist.version` (minor version bump), respectively. It would be a bug if this was not the case (linking of an executable with non-matching ABI wouldn't be prevented), but as these changes are part of the PR, it's ok.

IOW, if the "check_abi" fails, we need to verify that these changes are reflected by changes in the `.version` files. I'd love to automate this, but it's very difficult to get right the way libabigail currently works, and I prefer to be "on the safe side" with a manual check for every PR for now.

Once you merge these changes, the reference ABI in the "master" branch will be updated, and future PRs will fail this test only if they introduce new ABI changes.

**Comment by cvaroqui** [comment]
Thank for taking the time to explain.

**Comment by xosevp** [comment]
On 2/21/22 22:34, Martin Wilck wrote:

> here is another multipath-tools update. I've taken the liberty to bump the version to 0.8.9 already. It's mostly a bug fix release. The most important new feature is the support for FC Fibre 
> Performance Impact Notifications (FPIN) contributed by Muneendra Kumar.


It was not tagged yet!

**Comment by cvaroqui** [comment]
Tagged now. Thank you for the reminder Xose.

**Pull request merged**
